"""List of business names to exclude in response"""

# grocery = ['trader-joes', 'ralphs', 'vons', 'safeway', 'albertsons', 'whole-foods-market', 'sprouts-farmers-market',
#            'fresh-and-easy', 'gelsons', 'jons', 'save-mart', 'smart-and-final', 'kroger', 'shoprite', 'shop-rite']
# apparel = ['nordstrom', 'macys', 'ross', 'marshalls', 'aeropostale', 'american-apparel',
#            'american-eagle-outfitters', 'anthropologie', 'avenue',
#            'barneys-new-york',  'eddie-bauer', 'bebe', 'bergdorf-goodman', 'bloomingdales', 'buffalo-exchange',
#            'charlotte-russe', 'charming-charlie', 'chicos', 'club-monaco'
#            'davids-bridal', 'designer-bride', 'destination-bride', 'dillards', 'dsw-designer-shoe-warehouse', 'dkny',
#            'express', 'foot-locker', 'forever-21', 'fred-segal', 'fredericks-of-hollywood', 'gap', 'gilly-hicks',
#            'guess', 'gymboree', 'jcrew', 'lane-bryant', 'the-limited', 'saks-fifth-avenue', 'mens-warehouse',
#            'neiman-marcus', 'nordstrom-rack', 'pacsun', 'rei', 'talboots', 'tillys', 'urban-outfitters', 'wet-seal',
#            'burlington-coat-factory', 'old-navy', 'skechers', 'chicos', 'vans', 'havaianas', 'crocs', 'aerosoles', 'nike',
#            'payless-shoe-source', 'sanuk', 'shoe-city', 'loehmanns', 'torrid', 'victorias-secret', 'white-house-black-market',
#            'susser-holdings', 'belk', 'stater-holdings', 'ross-dress-for-less', 'carters-babies-and-kids']
# fooddrink = ['starbucks', 'wendys', 'subway', 'mcdonalds', 'burger-king', 'applebees', 'arbys', 'chick-fil-a',
#              'kfc', 'taco-bell', 'pizza-hut', 'ruby-tuesday', 'red-robin', 'chilis', 'dominos', 'papa-johns-pizza',
#              'jack-in-the-box', 'red-lobster', 'olive-garden', 'quiznos', 'outback-steakhouse', 'little-ceasears', 'carls-jr', 'popeyes', 'rainforest-cafe',
#              'panera-bread', 'hardees', 'tgi-fridays', 't-g-i-fridays', 'chipotle-mexican-grill', 'buffalo-wild-wings', 'charleys-grilled-subs',
#              'dunkin-donuts', 'in-n-out', 'tony-romas', 'shakeys-pizza', 'sizzler', 'corner-bakery', 'planet-hollywood', 'krispy-kreme', 'hooters',
#              'panda-express', 'five-guys', 'del-taco', 'peets-coffee-and-tea', 'coffee-bean-and-tea-leaf', 'baskin-robbins',
#              'dairy-queen', 'jamba-juice', 'cold-stone-creamery', 'yogurtland', 'golden-spoon-frozen-yogurt', 'dennys', 'ihop', 'popeyes',
#              'california-pizza-kitchen', 'romanos-macaroni-grill', 'el-pollo-loco', 'wahoos-fish-tacos', 'boston-market',
#              'tcby', 'white-castle', 'wing-street', 'round-table-pizza']
# sport = ['big-5-sporting-goods', 'sports-authority', 'dicks-sporting-goods', 'bass-pro-shops']
stores = ['walgreens', 'cvs', 'target', 'walmart', 'rite-aid', 'costco', 'kmart', 'barnes-and-noble', 'kohls',
          'tjmaxx', 'homegoods', 'cost-plus-world-market', '7-11', '7-eleven', 'best-buy', 'game-stop', 'toys-r-us', 'sephora',
          'ulta', 'michaels', 'jo-ann-fabric-and-craft', 'hobby-lobby', 'a-c-moore-arts-and-crafts',
          'bed-bath-and-beyond', 'ikea', 'pier-1-imports', 'pier-one-imports', 'william-sonoma', 'the-home-depot',
          'lowes', 'bevmo', 'menards', 'staples', 'office-max', 'office-depot', 'sams-club',
          'bjs-restaurant-and-brewhouse', 'sears', 'jcpenny', 'the-container-store', 'dollar-general-market',
          'trader-joes', 'ralphs', 'vons', 'safeway', 'albertsons', 'whole-foods-market', 'sprouts-farmers-market',
          'fresh-and-easy', 'gelsons', 'jons', 'save-mart', 'smart-and-final', 'kroger', 'shoprite', 'shop-rite',
          'nordstrom', 'macys', 'ross', 'marshalls', 'aeropostale', 'american-apparel', 'american-eagle-outfitters',
          'anthropologie', 'avenue', 'barneys-new-york',  'eddie-bauer', 'bebe', 'bergdorf-goodman', 'bloomingdales',
          'charlotte-russe', 'charming-charlie', 'chicos', 'club-monaco', 'davids-bridal',
          'designer-bride', 'destination-bride', 'dillards', 'dsw-designer-shoe-warehouse', 'dkny',
          'express', 'foot-locker', 'forever-21', 'fred-segal', 'fredericks-of-hollywood', 'gap', 'gilly-hicks',
          'guess', 'gymboree', 'jcrew', 'lane-bryant', 'the-limited', 'saks-fifth-avenue', 'mens-warehouse',
          'neiman-marcus', 'nordstrom-rack', 'pacsun', 'rei', 'talboots', 'tillys', 'urban-outfitters', 'wet-seal',
          'burlington-coat-factory', 'old-navy', 'skechers', 'chicos', 'vans', 'havaianas', 'crocs', 'aerosoles',
          'nike', 'payless-shoe-source', 'sanuk', 'shoe-city', 'loehmanns', 'torrid', 'victorias-secret',
          'white-house-black-market', 'susser-holdings', 'belk', 'stater-holdings', 'ross-dress-for-less',
          'carters-babies-and-kids', 'starbucks', 'wendys', 'subway', 'mcdonalds', 'burger-king', 'applebees',
          'arbys', 'chick-fil-a', 'kfc', 'taco-bell', 'pizza-hut', 'ruby-tuesday', 'red-robin', 'chilis',
          'dominos', 'papa-johns-pizza', 'jack-in-the-box', 'red-lobster', 'olive-garden', 'quiznos',
          'outback-steakhouse', 'little-ceasears', 'carls-jr', 'popeyes', 'rainforest-cafe', 'panera-bread',
          'hardees', 'tgi-fridays', 't-g-i-fridays', 'chipotle-mexican-grill', 'buffalo-wild-wings',
          'charleys-grilled-subs', 'dunkin-donuts', 'in-n-out', 'tony-romas', 'shakeys-pizza', 'sizzler',
          'corner-bakery', 'planet-hollywood', 'krispy-kreme', 'hooters', 'panda-express', 'five-guys', 'del-taco',
          'peets-coffee-and-tea', 'coffee-bean-and-tea-leaf', 'baskin-robbins', 'dairy-queen', 'jamba-juice',
          'cold-stone-creamery', 'yogurtland', 'golden-spoon-frozen-yogurt', 'dennys', 'ihop', 'popeyes',
          'california-pizza-kitchen', 'romanos-macaroni-grill', 'el-pollo-loco', 'wahoos-fish-tacos',
          'boston-market', 'tcby', 'white-castle', 'wing-street', 'round-table-pizza', 'big-5-sporting-goods',
          'sports-authority', 'dicks-sporting-goods', 'bass-pro-shops', 'petco', 'petsmart', 'wells-fargo',
          'bank-of-america', 'chase-bank', 'citibank', 'stater-bros', 'pavillions', 'pinkberry', 'piraat-pizzeri',
          'reasors',
          'buffalo-exchange', 'goodwill-industries', 'the-salvation-army']
